version: '3.8'

services:
  database:
    container_name: database
    image: mysql:latest
    environment:
      MYSQL_DATABASE: unkey
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - unkey-db:/var/lib/mysql

volumes:
  unkey-db:
